### ISSUE TITLE
Renault Server Error 502+504

### ISSUE THREAD

**Issue by DPO99** [TA2k/ioBroker.renault#14]
**Describe the bug**  
Seit dieser Woche sehr viele 502+504 Fehler im Log

**To Reproduce**  
Adapter anschalten und warten.

**Expected behavior**  
Keine Fehler

**Screenshots & Logfiles**  

`<html>
<body>

renault.0 | 2023-05-17 17:13:39.570 | warn | Renault Server error: 502
-- | -- | -- | --
renault.0 | 2023-05-17 17:13:39.425 | warn | Renault Server error: 502
renault.0 | 2023-05-17 17:13:39.222 | warn | Renault Server error: 504
renault.0 | 2023-05-17 17:12:39.037 | warn | Renault Server error: 500
renault.0 | 2023-05-17 17:12:07.379 | warn | Renault Server error: 504
renault.0 | 2023-05-17 17:11:07.203 | warn | Renault Server error: 504
renault.0 | 2023-05-17 17:10:07.071 | warn | Renault Server error: 502
renault.0 | 2023-05-17 17:09:46.365 | warn | Renault Server error: 504
renault.0 | 2023-05-17 17:08:46.132 | warn | Renault Server error: 504
renault.0 | 2023-05-17 17:07:45.987 | warn | Renault Server error: 504
renault.0 | 2023-05-17 14:36:49.025 | warn | Renault Server error: 500
renault.0 | 2023-05-17 14:36:48.628 | warn | Renault Server error: 500
renault.0 | 2023-05-17 14:36:48.305 | warn | Renault Server error: 500
renault.0 | 2023-05-17 14:36:48.050 | warn | Renault Server error: 500
renault.0 | 2023-05-17 14:36:47.782 | warn | Renault Server error: 500
renault.0 | 2023-05-17 14:36:47.414 | warn | Renault Server error: 500

</body>
</html>`

**Versions:**  
 - Adapter version: <0.0.17>
 - JS-Controller version: <4.0.24>
 - Node version: <v18.16.0>
 - Operating system: <Raspbian Bullseye>

**Additional context**  
Habt Ihr ähnliche Probleme und es liegt an Renault oder liegt das Problem ggf. bei mir?

**Comment by Blackbat72** [comment]
Hab seit einiger Zeit auch das gleiche Probelm - allerdings nur 502

**Comment by TA2k** [comment]
Ich gehe davon aus das es Ausfälle bei Renault aus
