### ISSUE TITLE
Werte ändern

### ISSUE THREAD

**Issue by Zengaja** [TA2k/ioBroker.renault#8]
Hi,

erstmal vielen Dank für deine Arbeit diesen Adapter zu programieren.
Im Gegensatz zum Zoe.Adapter liest deiner hier wesendlich mehr Werte aus, was ich mir immer wünschte.

Der Adapter ist zwar noch früh in der Entwicklung aber ich frage dennnoch: Das man die Werte ändern kann, kommt das noch?
zb Laden starten und Beenden, programierbare Ladenzeiten einstellen, etc...

Zum Thema "last changes", könntest du das so einstellen das man selbst auswählen kann wie weit man zurück gehen möchte und nicht fest 14 Tage?

Vielen Dank und mach weiter so :)

**Comment by TA2k** [comment]
unter .remote können Sachen geändert werden
ich glaube länger als 14 Tage ist nicht möglich

**Comment by Zengaja** [comment]
Hi,

Danke für die Info :)

Was ist der Unterschied zwischen actions/charging-start & charge/start? Wenn ich das richtig sehe sind beide für den Start des Ladevorgangs.

Funktioniert das Stoppen des Ladevorgangs mit charge/pause-resume? Weil mit anderen Adaptern funktioniert diese Funktion nicht. Da muss man Umwege gehen zb über programierbare Ladezeiten.

**Comment by TA2k** [comment]
Kann ich nicht beantworten habe kein renault
